service: account-admin
runtime: python
env: flex
entrypoint: gunicorn -b :$PORT admin_app:app

runtime_config:
  python_version: 3

env_variables:
  DBURL: >- 
    postgres://account_admin_user@/account_admin_master?host=/cloudsql/lexical-cider-93918:us-central1:pg-master
  PGPASSWORD: "qqqWww111"
  PROJECT_NUMBER: 863717576768
  PROJECT_ID: lexical-cider-93918

beta_settings:
    cloud_sql_instances: lexical-cider-93918:us-central1:pg-master
